target-version = "py313"

line-length = 88
indent-width = 4

src = ["src"]

[lint]
select = ["ALL"]
ignore = [
    "ARG",
    "ANN",
    "D",
    "EM101",
    "EM102",
    "PT001",
    "PT023",
    "SIM108",
    "SIM114",
    "TRY003",
    "TC003",
    "PLW2901",
    "RET505",
    "PLR0913",
    "UP038",
    "TC001",
    "TC002",
    "SIM103",
    "ISC003",
    "PTH123",
    "UP007",
    "PTH103",
    "A002",
    "T201",
    "S311",
    "C901",
    "DTZ",
    "RUF",
    "PLR2004",
    "PLR0912",
    "A001",
    "E501",
]