[project]
name = "coursework"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.13"

[dependency-groups]
lint = ["ruff"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
